# MoneyBag — release-build R8 rules.
#
# WHY THIS FILE EXISTS
# --------------------
# Flutter 3.24's gradle plugin enables R8 minification for release builds
# (flutter.groovy: minifyEnabled(true)) and auto-includes this file.
# Without the rules below, R8 obfuscates Gson's TypeToken and strips the
# generic Signature attribute. flutter_local_notifications then throws
#     PlatformException(error, Missing type parameter., ...)
# on every zonedSchedule() call — daily/weekly reminders silently never
# get scheduled. Verified on device (2026-09-12).

# 1) Keep the whole notifications plugin — its model classes are
#    (de)serialized by Gson, so names and fields must survive.
-keep class com.dexterous.** { *; }

# 2) Official Gson rules (google/gson android-proguard-example).
#    TypeToken MUST keep its Signature so generics resolve at runtime.
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken
-keepattributes Signature
-keepattributes RuntimeVisibleAnnotations,RuntimeVisibleParameterAnnotations
-keepattributes AnnotationDefault
-dontwarn sun.misc.**

# 3) Play-services / Firebase use reflection on these — keep safe.
-dontwarn com.google.android.gms.**
-dontwarn com.google.firebase.**

# 4) v2.1 Receipt OCR (google_mlkit_text_recognition 0.11) — the plugin's
#    MethodChannel references optional script recognizers (chinese, devanagari,
#    japanese, korean) that live in separate ML Kit artifacts we do NOT bundle.
#    MoneyBag uses the default Latin v2 model, so these are safe to ignore.
#    Rules below are auto-generated by AGP (missing_rules.txt, 2026-09-13).
-dontwarn com.google.mlkit.vision.text.chinese.**
-dontwarn com.google.mlkit.vision.text.devanagari.**
-dontwarn com.google.mlkit.vision.text.japanese.**
-dontwarn com.google.mlkit.vision.text.korean.**
